### ISSUE TITLE
may be there are more telegrams IPs

### ISSUE THREAD

**Issue by vgdh** [lord-alfred/ipranges#17]
This [site ](https://ipinfo.io/AS62041#block-ranges) claims there is more IPs  in telegram networks

149.154.160.0/22 	Telegram Messenger Network 	1,024
149.154.160.0/23 	Telegram Messenger Network 	512
149.154.162.0/23 	Telegram Messenger Network 	512
149.154.164.0/22 	Telegram Messenger Network 	1,024
149.154.164.0/23 	Telegram Messenger Network 	512
149.154.166.0/23 	Telegram Messenger Network 	512
91.108.4.0/22 	Telegram Messenger Network 	1,024
91.108.56.0/22 	Telegram Messenger Network 	1,024
91.108.8.0/22 	Global Network Management Inc 	1,024
95.161.64.0/20 	Telegram Messenger Inc 	4,096

**Comment by Ketanest** [comment]
As you can see with a subnet calculator, the 149.154.160.0/20 includes all of the mentioned 149.x networks.
The 95.161.64.0/20 ist the only not published by telegram itself. I would trust the IPs published by telgram because they know best what addresses they use. Extracting IPs from ipinfo would require an expensive subscription.

**Comment by vgdh** [comment]
ok thank you
